/********************************************************************
* Cint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Cint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCint();
extern void G__cpp_setup_inheritanceCint();
extern void G__cpp_setup_typetableCint();
extern void G__cpp_setup_memvarCint();
extern void G__cpp_setup_globalCint();
extern void G__cpp_setup_memfuncCint();
extern void G__cpp_setup_funcCint();
extern void G__set_cpp_environmentCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JsonElement.h"
#include "FormulaLooter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CintLN_string;
extern G__linked_taginfo G__CintLN_basic_ostringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CintLN_JsonElement;
extern G__linked_taginfo G__CintLN_JsonObject;
extern G__linked_taginfo G__CintLN_JsonArray;
extern G__linked_taginfo G__CintLN_JsonFixed;
extern G__linked_taginfo G__CintLN_JsonSigFig;
extern G__linked_taginfo G__CintLN_TTree;
extern G__linked_taginfo G__CintLN_pairlEstringcOstringgR;
extern G__linked_taginfo G__CintLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__CintLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
