#include <TFile.h>
#include <TTree.h>
#include <TProfile.h>
#include <TF1.h>
#include <fstream>

using std::endl;


void outfit(ofstream& out, TProfile* p) 
{
  if(fabs(p->GetFunction("pol1")->GetParameter(1)) > 0.001)
  out << p->GetFunction("pol1")->GetParameter(0) 
            << "+wire*(" << p->GetFunction("pol1")->GetParameter(1) 
            << ");" << endl;
  else
    out << p->GetFunction("pol1")->GetParameter(0) << ";" << endl;
    
}

void fitgeo()
{
  ofstream out("geo.js");
  out << "// Code automagically generated by fitgeo.C " << endl;
  TFile* f = new TFile("geodump.root");
  TTree* tree = (TTree*) f->Get("geo");
  TProfile* p = new TProfile("p","profile",3500,0,3500);
  TH1F*     ht = new TH1F("ht","ht",6000,-300,300);
  out << std::fixed;
  out.precision(3);
  out << "  // Code automagically generated by fitgeo.C " << endl;
  out << "Geometry.prototype.getWire = function(plane,wire) " << endl;
  out << "{ " << endl;
  
  out << "  var r={};" << endl;
  out << "  switch(plane) {" << endl;
  
  for(int plane=0;plane<3;plane++) {
    out << "    case " << plane << ":" << endl;
    const char* planecut = Form("plane==%d",plane);

    // X is electron drift direction.
    tree->Draw("x>>ht",planecut);
    out << "      r.cx = " << ht->GetMean() << ";" << endl;

    // Wire center coordinates.
    int sections = 3;
    if(plane==2) sections = 1;
    for(int section=0;section<sections;section++) {
      int wirelow = 0;
      int wirehigh = 0;
      if(plane<2) {          
      
        if(section ==0 ) {
           wirelow = 0; wirehigh = 671;
           out << "      if(wire<" << wirehigh << ") {" << endl;
        }
        if(section ==1 ) { 
          wirelow = 671; wirehigh = 1727; 
          out << "      } else if(wire<" << wirehigh << ") {" << endl;
      
        }
        if(section ==2 ) { 
          wirelow = 1727; wirehigh = 2398; 
          out << "      } else {" << endl;;
        }
    } else {
      // plane == 2
      wirelow = 0;
      wirehigh = 3455;
    }
    out << "        r.section = " << section << ";" << endl;
    tree->Draw("y:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.cy = ";
    outfit(out,p);
    
    tree->Draw("z:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.cz = ";
    outfit(out,p);
    // out << "      cz = " << p->GetFunction("pol1")->GetParameter(0) 
    //       << "+wire*(" << p->GetFunction("pol1")->GetParameter(1) 
    //       << ");" << endl;


    tree->Draw("y-halfl*sin(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.y1 = ";
    outfit(out,p);

    tree->Draw("y+halfl*sin(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.y2 = ";
    outfit(out,p);

    tree->Draw("z-halfl*cos(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.z1 = ";
    outfit(out,p);

    tree->Draw("z+halfl*cos(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.z2 = ";
    outfit(out,p);

    tree->Draw("halfl:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.halfl = ";
    outfit(out,p);

    tree->Draw("thetaz:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "        r.thetaz = ";
    outfit(out,p);

   }   
   if(plane<2) {          
     out << "      }" << endl;
   }
   out << "    break; " << endl;
  }
  out << "  }" << endl;
  out << "  return r;" <<endl;
  out << "}" << endl;
  
  out << endl << endl;

  p = new TProfile("p","profile",2000,-1000,1000);
  out.precision(5);
  out << "  // Code automagically generated by fitgeo.C " << endl;
  out << "Geometry.prototype.yzToWire = function(plane,y,z)" << endl;
  out << "{" << endl;
  out << " switch(plane) {" << endl;
  out << "   case 0:" << endl;
  out << "      var trans= this.kU[0]*z + this.kU[1]*y;" << endl;
  tree->Draw("wire:cos(TMath::Pi()/3)*z-sin(TMath::Pi()/3)*y>>p","plane==0");
  p->Fit("pol1","WQ","G");
  out << "      var wire = " << p->GetFunction("pol1")->GetParameter(0) 
            << "+trans*(" << p->GetFunction("pol1")->GetParameter(1) 
            << ");" << endl;
  out << "      break;" << endl;

  out << "   case 1:" << endl;
  out << "      var trans= this.kV[0]*z + this.kV[1]*y;" << endl;
  tree->Draw("wire:cos(TMath::Pi()/3)*z+sin(TMath::Pi()/3)*y>>p","plane==1");
  p->Fit("pol1","WQ","G");
  out << "      var wire = " << p->GetFunction("pol1")->GetParameter(0) 
            << "+trans*(" << p->GetFunction("pol1")->GetParameter(1) 
            << ");" << endl;
  out << "      break;" << endl;


  out << "   case 2:" << endl;
  tree->Draw("wire:z>>p","plane==2");
  p->Fit("pol1","WQ","G");
  out << "      var wire = " << p->GetFunction("pol1")->GetParameter(0) 
            << "+z*(" << p->GetFunction("pol1")->GetParameter(1) 
            << ");" << endl;
  out << "      break;" << endl;


  out << " }" << endl;
  out << "  return Math.round(wire);" << endl;
  out << "}" << endl;
  
}