#include <TFile.h>
#include <TTree.h>
#include <TProfile.h>
#include <TF1.h>
#include <fstream>

using std::endl;


void outfit(ofstream& out, TProfile* p) 
{
  if(fabs(p->GetFunction("pol1")->GetParameter(1)) > 0.001)
  out << p->GetFunction("pol1")->GetParameter(0) 
            << "+wire*(" << p->GetFunction("pol1")->GetParameter(1) 
            << ");" << endl;
  else
    out << p->GetFunction("pol1")->GetParameter(0) << ";" << endl;
    
}

void fitgeo()
{
  ofstream out("geo.js");
  out << "// Code automagically generated by fitgeo.C " << endl;
  TFile* f = new TFile("geodump.root");
  TTree* tree = (TTree*) f->Get("geo");
  TProfile* p = new TProfile("p","profile",3500,0,3500);
  TH1F*     ht = new TH1F("ht","ht",6000,-300,300);
  out << std::fixed;
  out.precision(3);
  out << "var wire={};" << endl;
  out << "switch(plane) {" << endl;
  
  for(int plane=0;plane<3;plane++) {
    out << "  case " << plane << ":" << endl;
    const char* planecut = Form("plane==%d",plane);

    // X is electron drift direction.
    tree->Draw("x>>ht",planecut);
    out << "    wire.cx = " << ht->GetMean() << ";" << endl;

    // Wire center coordinates.
    int sections = 3;
    if(plane==2) sections = 1;
    for(int section=0;section<sections;section++) {
      int wirelow = 0;
      int wirehigh = 0;
      if(plane<2) {          
      
        if(section ==0 ) {
           wirelow = 0; wirehigh = 671;
           out << "    if(wire<" << wirehigh << ") {" << endl;
        }
        if(section ==1 ) { 
          wirelow = 671; wirehigh = 1727; 
          out << "    } else if(wire<" << wirehigh << ") {" << endl;
      
        }
        if(section ==2 ) { 
          wirelow = 1727; wirehigh = 2398; 
          out << "    } else {" << endl;;
        }
    } else {
      // plane == 2
      wirelow = 0;
      wirehigh = 3455;
    }
    tree->Draw("y:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      cy = ";
    outfit(out,p);
    
    tree->Draw("z:wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      cz = ";
    outfit(out,p);
    // out << "      cz = " << p->GetFunction("pol1")->GetParameter(0) 
    //       << "+wire*(" << p->GetFunction("pol1")->GetParameter(1) 
    //       << ");" << endl;


    tree->Draw("y-halfl*sin(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      y1 = ";
    outfit(out,p);

    tree->Draw("y+halfl*sin(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      y2 = ";
    outfit(out,p);

    tree->Draw("z-halfl*cos(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      z1 = ";
    outfit(out,p);

    tree->Draw("z+halfl*cos(thetaz):wire>>p",planecut);
    p->Fit("pol1","WQ","G",wirelow,wirehigh);
    out << "      z2 = ";
    outfit(out,p);
   }   
   if(plane<2) {          
     out << "    }" << endl;
   }
   out << "  break; " << endl;
  }
  out << "}";
}