<table border="0" style="display:inline;"><tr>
   <td><img src="images/Otterbein.png" width="100px" height="100px" /></td>
   <td>
     uBoone Online Monitor, Built and Maintained by <a href="http://faculty.otterbein.edu/NTagg">Nathaniel Tagg</a>,
       <a href="http://www.otterbein.edu">Otterbein College</a><br/>   
     Send any comments, bug reports, or suggestions to <a href="mailto:ntagg@otterbein.edu">Nathaniel</a>.<br/>
     This work is supported by the <a href="http://www.nsf.gov">National Science Foundation</a>.<br/>
   </td>
   <td>
     <img src="images/ublogo.jpg" height="100px" />
   </td>
   </tr>
</table>
