<table style="display:inline; border:0;"><tr>
   <td><img src="images/Otterbein.png" width="100" height="100" alt="logo"/></td>
   <td>
     Argo Event Display, Built and Maintained by <a href="http://faculty.otterbein.edu/NTagg">Nathaniel Tagg</a>,
       <a href="http://www.otterbein.edu">Otterbein College</a><br/>
   
     Send any comments, bug reports, or suggestions to Nathaniel at NTagg (at) otterbein.edu.<br/>
     This work is supported by the <a href="www.nsf.gov">National Science Foundation</a>.<br/>
     <p style="font-size: 0.875em">About the name <a href="http://argo-microboone.fnal.gov/help/#argo">Argo</a></p>
   </td>
   <td>
     <img src="images/ublogo.jpg" height="100" alt="ublogo" />
   </td>
   </tr>
</table>
