<div class="portlet" id="dedx-port"> 
<div class="portlet-header">dE/dX Tool</div>
  <div  class="portlet-content">
      <div class="dEdXTool-control">
        <label><input type="checkbox" class="dEdX-Path" value="1" />Show dEdX Path</label><br/>
        <div class="dEdX-width-slider" style="width:100;"></div><br/>
        <label><input type="text" class="dEdX-width-text" value="10" size='2'>Path Width</label>
      </div>
      <div class="A-dEdXTool" style="height:200px"></div>
  </div>
</div>  <!-- portlet -->
