<div class="portlet" id="eventinfo-port"> 
<div class="portlet-header">Event Info</div>
  <div  class="portlet-content">
    <div class="A-EventInfo">
      <table class="eventinfo"><tbody>
        <tr><td class="key">Run</td>        <td class="val event-run">?</td></tr>
        <tr><td class="key">SubRun</td>     <td class="val event-subrun">?</td></tr>
        <tr><td class="key">Event</td>      <td class="val event-event">?</td></tr>
        <tr><td class="key">Data Type</td>  <td class="val event-datatype">MC</td></tr>
        <tr><td class="key">Date:</td>      <td><span class="val event-date"></span><br>
                                                <span class="val event-time"></span><br>
                                                <span class="val event-age"></span></td></tr>

        <tr><td class="key">Entry</td>      <td><span class="val event-entry">?</span>/<span class="val event-numEntriesInFile"></span></td></tr>
        <tr><td class="key">Raw Wires</td>  <td class="val event-raw-wire-names"></td></tr>
        <tr><td class="key">Cal Wires</td>  <td class="val event-cal-wire-names">Not present</td></tr>
        <tr><td class="key">Hits</td>       <td class="val event-hit-names">none</td></tr>
        <tr><td class="key">Clusters</td>   <td class="val event-cluster-names">none</td></tr>
        <tr><td class="key">SpacePoints</td><td class="val event-spacepoint-names">none</td></tr>
        <tr><td class="key">Tracks</td>     <td class="val event-track-names">none</td></tr>
        <tr><td class="key">Showers</td>     <td class="val event-shower-names">none</td></tr>
        <tr><td class="key">Optical Pulses</td> <td class="val event-oppulse-names">none</td></tr>
        <tr><td class="key">Optical Hits</td>   <td class="val event-ophit-names">none</td></tr>
        <tr><td class="key">Optical Flashes</td>  <td class="val event-opflash-names">none</td></tr>
      </tbody></table>
    </div>
  </div>
</div>  <!-- portlet -->
