    <div class="portlet" id="hit-map-port"> 
      <div class="portlet-header">Hit Maps</div>
      <div id="hitmaps" class="portlet-content">
        
        <div style="width: 33%;float: left;">
          <span><center>X View</center></span>
          <div class="pad" style="width: 100%;  height:160px;" id="xz" settings="margin_left:38, margin_bottom:35 ,ylabel:'Time', xlabel:'Wire', label_font:'12px sans-serif'"></div>
        </div>

        <div style="width: 33%; float: right">
          <span><center>U View</center></span>
          <div class="pad" style="width: 100%; height:160px;" id="vz" settings="margin_left:38, margin_bottom:35 ,ylabel:'Strip', xlabel:'Wire', label_font:'12px sans-serif'"></div>
        </div>

        <div style="width: 33%; margin-left: 33%"            >
          <span><center>V View</center></span>
          <div class="pad"  style="width: 100%;  height:160px;" id="uz" settings="margin_left:38, margin_bottom:35 ,ylabel:'Strip', xlabel:'Wire', label_font:'12px sans-serif'"></div>
        </div>

      </div>
    </div>

