<!-- Message of the Day. -->
<div id="MOTD" style="display:none;"> 
  <img style='float:left; padding: 10px;' src="images/busy.gif" /> 
  <p>Querying server for event data...</p>
  <p><em>Message of the day:</em></p>
  <p>Welcome to the new MicroBoone Event Display.</p>
  <p>This is an beta-test software, so please wear appropriate personal safety equipment.</p>
  </p>
  Recent updates: <br/>
  <ul>
    <li> MC and Track Hover/Select now working correctly in wire/MC digraph views.</li>
    <li> Starting to more elegantly handle multiple data products in one file.</li>
    <li> Fixed Ryan's problems seeing MC from particle cannon.</li>
  </ul>
</div> 
