<!-- Message of the Day. -->
<div id="MOTD" style="display:none;"> 
  <img style='float:left; padding: 10px;' src="images/busy.gif" /> 
  <p>Querying server for event data...</p>
  <p><em>Message of the day:</em></p>
  </p>
  Recent updates: <br/>
  <ul>
    <li> NEW: Click to select tracks or trajectories, with popup info overlay!
    <li> MC and Track Hover/Select now working correctly in wire, 3D, and MC digraph views.</li>
  </ul>
</div> 
