<!-- Message of the Day. -->
<div id="MOTD" style="display:none;"> 
  <div id="load-progressbar"></div>
  <!-- <img style='float:left; padding: 10px;' src="images/busy.gif" alt="busy"/> -->
  <img style='float:left; padding: 10px;width:80px' src="images/cool2.gif" alt="busy"/>
  <p>Querying server for event data...</p>
  <div id="loading_feedback"></div>
  <p><em>Message of the day:</em></p>
  Recent updates: <br/>
  <ul> 
    <li> FIXED false-color display artifacts - detector looks cleaner now! </li>
    <li> ADDED ADC cutoffs for Tia</li>
    <li> FIXED Removed blur on copy-from-offscreen</li>
    <li> IMPROVE Build-textures-on-the-go. 25% speedup in first wire render, even faster on changing color scale.</li>
    
  </ul>
</div> 
