<div class="portlet" id="mri-port"> 
  <div class="portlet-header">"MRI" Timeslice View</div>
  <div class="portlet-content">
    <div class="A-MRI" style="height: 300px; width: 100%"></div>
    <span class="MRI-Info"></span>
    <!-- <span class="align-right" style="width: 35px;">
      <input type="checkbox" class="align-right mri-autoscan" id="mri-autoscan1" /><label for="mri-autoscan1">AutoScan</label>
    </span> -->
    <div >
    <div>Window:  <div class="mri-slider-window-size" style="display:inline-block; width: 50%;  margin: 5px; "></div>     </div>
    <!-- <div>Ends:    <div class="mri-slider-ends"        style="display:inline-block; width: 80%;  margin: 5px; "></div>     </div> -->
    <div>Position:
      <div>
        <span class="align-left mri-slider-grip-size-nudge-left">nudgeleft</span>
        <span class="align-right mri-slider-grip-size-nudge-right">nudgeright</span>        
        <div class="mri-slider-grip"  style="display:inline-block; width: 50%; margin-left: 50px;  margin-right: 50px "></div>
      </div>
    </div>

  </div>
  </div>
</div>


