<div class="portlet" id="omstatus-port"> 
<div class="portlet-header">Online Monitor Status</div>
  <div  class="portlet-content">
    <div class="A-OmStatus">
      <div class="statusinfo" ></div>
      <button class="refresh">Refresh</button>
      <input type="checkbox" id="ctl-auto-refresh"   class="ctl-autosave ctl-auto-refresh">Auto-Refresh</input>
      <input type="checkbox" id="ctl-low-resolution" class="ctl-autosave ctl-low-resolution">Low Resolution (faster)</input>
      
    </div>
  </div>
</div>  <!-- portlet -->
