    <div class="portlet" id="opflash-port"> 
      <div class="portlet-header">Optical Flashes</div>
      <div class="portlet-content">
        <div style="width: 49%;float: left;">
          <div class="A-OpFlashHistogram" style="height: 120px"></div>
        </div>
        <div style="width: 49%;float: right;">
          <div class="A-OpFlashMap" style="height: 120px"></div>
        </div>
        <div class="A-OpFlash2dMap" style="clear:both; height: 250px"></div>
        
      </div> <!-- portlet-content -->
    </div> <!-- portlet -->

