    <div class="portlet" id="ophit-port"> 
      <div class="portlet-header">Optical Hits</div>
      <div class="portlet-content">
        <div style="width: 49%;float: left;">
          <div class="A-OpHitHistogram" style="height: 120px"></div>
        </div>
        <div style="width: 49%;float: right;">
          <div class="A-OpHitMap" style="height: 120px"></div>
        </div>
        <div class="A-OpHit2dMap" style="clear:both; height: 250px"></div>
        
      </div> <!-- portlet-content -->
    </div> <!-- portlet -->

