<div class="portlet" id="pf-digraph-portlet">
    <!-- <link rel="stylesheet" href="digraph.css" type="text/css" media="all"/> -->
    
    <div class="portlet-header"><span class="title">PFParticle Digraph</span></div>
    <div class="portlet-content" >
        <div  id="PFDigraph-1" class="A-PFDigraph squeezable" style='height: 300px; background-color:white'></div>
        <button id='ctl-switch-to-pandora'>Switch to Associated Pandora Products</button>
    </div> 
</div>