<script type="text/javascript" src="libs/reco.js"></script> 

<div class="portlet" id="reco-port">
  <div class="portlet-header">Reco</div>
  <div class="portlet-content">
      <div class="A-reco">
        <div><input type="checkbox" id="ctl-show-reco"  name="show-reco"      class="saveable show-reco" 
               checked="yes"/><label for="ctl-show-reco">      <b>(r)</b> Show Reco </label></div>
        
        <button class="reco-go-button">Go!</button>
        <div class="A-reco-pad"></div>
        <div class="A-reco-text"></div>
      </div>
  </div> <!-- portlet-content -->
</div> <!-- portlet -->
