<div id="selected-object-info" class="triangle-isosceles left floating ui-widget-content">
  <div class="selected-object-info"></div>
  <!-- <div class="unit-ctl" style="display:none;">
      <input type="radio"  name="unit-ctl" id="unit-radio1" value="MeV" checked="checked"/><label for="unit-radio1">MeV</label>
      <input type="radio"  name="unit-ctl" id="unit-radio2" value="SI" />             <label for="unit-radio2">SI</label>
  </div> -->
</div>
