<div class="portlet" id="bigwireimg-port"> 
<div class="portlet-header">Big Wire View</div>
<div class="portlet-content">
  
    <div id="BigWireView" class="pad A-WireView" style="width:100%; height:300px" 
      data-options='{"plane": 2, "zooming": false, "margin_left": 50}'></div>
    <span class="bigwireview-select align-right">
      <input type="radio" class="bigwireview-select-button" name='wireview-select' id="bigwireview-select-0" value='0' />
      <label for="bigwireview-select-0">Plane 0</label>

      <input type="radio" class="bigwireview-select-button" name='wireview-select' id="bigwireview-select-1" value='1'  />
      <label for="bigwireview-select-1">Plane 1</label>                                            

      <input type="radio" class="bigwireview-select-button" name='wireview-select' id="bigwireview-select-2" value='2'  checked="yes" />
      <label for="bigwireview-select-2">Plane 2</label>

    </span>
</div> <!-- portlet-content -->

</div>  <!-- portlet -->
