<div class="portlet" id="wireimg-port"> 
<div class="portlet-header">Zoomed Wire Views</div>
<div class="portlet-content" style="background-color:white">

  <div style="width: 33%;float: left;">
   <center> <span style="color: red">"U" View / View 2 / Plane 0</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 0"></div>
  </div>
  
  <div style="width: 33%;float: right;">
    <center> <span style="color: blue">"Y" View / View 0 /Plane 2</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 2"></div>
  </div>

  <div style="width: 33%; margin-left: 33.35%"            >
    <center> <span style="color: green">"V" View / View 1 / Plane 1</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 1"></div>
  </div>
  <div style="clear: both;"></div>

  <div style="width: 33%;float: left;">
    <div class="pad A-WireHistogram" style="width:100%; height:100px" settings="plane: 0"></div>
  </div>
  
  <div style="width: 33%;float: right;">
    <div class="pad A-WireHistogram" style="width:100%; height:100px" settings="plane: 2"></div>
  </div>

  <div style="width: 33%; margin-left: 33.35%"            >
    <div class="pad A-WireHistogram" style="width:100%; height:100px" settings="plane: 1"></div>
  </div>

</div> <!-- portlet-content -->
</div>  <!-- portlet -->
