<div class="portlet" id="wireimg-port-0"> 
  <div class="portlet-header">Plane 0 (Induction)</div>
  <div class="portlet-content" style="background-color:white">
      <div class="pad A-WireView" style="width:100%; height:330px" data-options='{"plane":0}'></div>
  </div>
</div>


<div class="portlet" id="wireimg-port-1"> 
  <div class="portlet-header">Plane 1 (Induction)</div>
  <div class="portlet-content" style="background-color:white">
      <div class="pad A-WireView" style="width:100%; height:330px" data-options='{"plane":1}'></div>
  </div>  
</div>

<div class="portlet" id="wireimg-port-2"> 
  <div class="portlet-header">Plane 2 (Collection)</div>
  <div class="portlet-content" style="background-color:white">
      <div class="pad A-WireView" style="width:100%; height:330px" data-options='{"plane":2}'></div>
      <div>
        <input type="checkbox" name="ctl-lock-aspect-ratio" class="ctl-lock-aspect-ratio saveable" checked="checked"/><label style='color: black;' for="ctl-lock-aspect-ratio">Lock TDC/Wire aspect ratio</label>
      </div>

  </div>
</div>



