<div class="portlet" id="wireimg-port" style="height: 550px;"> 
<div class="portlet-header">Zoomed Wire Views</div>
<div class="portlet-content" style="background-color:white;">

  <div style="width: 33%;float: left;  position: relative;">
    <span style="background: green; color: red; "><center>"U" View / View 2 / Plane 0</center></span>
      <div class="pad A-WireView"      style="width:33%; height:75%; position: absolute;" data-options='{"plane": 0}'></div>
      <div class="pad A-WireHistogram" style="width:33%; height:20%; position: absolute; bottom:0;" data-options='{"plane": 0}'></div>
  </div>
  
  <div style="width: 33%;float: right;">
    <center> <span style="color: blue">"Y" View / View 0 /Plane 2</span></center>
    <div class="pad A-WireView"      style="width:33%; height:75%; position: absolute;" data-options='{"plane": 2}'></div>
    <div class="pad A-WireHistogram" style="width:33%; position: absolute; bottom:0;" data-options='{"plane": 2}'></div>
    
  </div>

  <div style="width: 33%; margin-left: 33.35%"            >
    <center> <span style="color: green">"V" View / View 1 / Plane 1</span></center>
      <div class="pad A-WireView"      style="width:33%; height:75%; position: absolute;" data-options='{"plane": 1}'></div>
      <div class="pad A-WireHistogram" style="width:33%; height:20%; position: absolute; bottom:0;" data-options='{"plane": 1}'></div>
    </div>
  </div>

  <div style="clear: both;"></div>

</div> <!-- portlet-content -->
</div>  <!-- portlet -->
