<div class="portlet" id="wireimg-port"> 
<div class="portlet-header">Wire Data</div>
<div id="calib" class="portlet-content">
  
<div>
  <div style="width: 29%;float: left;">
    <span style="center">Calibrated Plane 0</span>
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 0, obj:'cal'"></div>
  </div>
  
  <div style="width: 42%;float: right;">
    <span style="center">Calibrated Plane 2</span>
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 2, obj:'cal'"></div>
  </div>

  <div style="width: 29%; margin-left: 29%"            >
    <span style="center">Calibrated Plane 1</span>  
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 1, obj:'cal'"></div>
  </div>
</div>


<div>
  <div style="width: 29%;float: left;">
    <span style="center">Raw View 0</span>
    
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 0, obj:'raw'"></div>
  </div>
  
  <div style="width: 42%;float: right;">
    <span style="center">Raw View 2</span>
    
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 2, obj:'raw'"></div>
  </div>

  <div style="width: 29%; margin-left: 29%">
    <span style="center">Raw View 1</span>    
    <div class="pad A-WireImg" style="width:100%; height:300px" settings="plane: 1, obj:'raw'"></div>
  </div>
</div>


</div>
</div>  <!-- portlet -->
