<div class="portlet" id="wireimg-port"> 
<div class="portlet-header">Zoomed Wire Views</div>
<div class="portlet-content" style="background-color:white">

  <div style="width: 33%;float: left;">
   <center> <span style="color: black">Plane 0</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 0, show_mc:true,show_image:'cal'"></div>
  </div>
  
  <div style="width: 33%;float: right;">
    <center> <span style="color: black">Plane 2</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 2, show_mc:true,show_image:'cal'"></div>
  </div>

  <div style="width: 33%; margin-left: 33.35%"            >
    <center> <span style="color: black">Plane 1</span></center>
    <div class="pad A-WireView" style="width:100%; height:300px" settings="plane: 1, show_mc:true,show_image:'cal'"></div>
  </div>
  
</div> <!-- portlet-content -->
</div>  <!-- portlet -->
