<div class="portlet" id="zoomcontrol-port"> 
  <div class="portlet-header">Zoom Control</div>
  <div class="portlet-content">
    <div class="A-ZoomControl"></div>
    <span class="ZoomControl-Info"></span>
    <span class="ZoomControl-Controls align-right">
      <button type="button" class="zoom-auto">Auto</button>
      <button type="button" class="zoom-full">Full</button>
    </span>
  </div>
</div>

